### ISSUE TITLE
HTTP2 Upstream

### ISSUE THREAD

**Issue by ronag** [nxtedition/node-http2-proxy#3]

**Comment by paambaati** [comment]
@ronag Is this the same as proxying a request to a HTTP/2 server?

**Comment by petermelias** [comment]
@ronag Just out of curiosity -- are you waiting to implement this because of the Node `http2` module still being marked as experimental, or is it just in your backlog?

I ask because I was hoping to do `http2`->`http2` proxying and since this doesn't support it yet I may just try and do it directly via the `http2` module given it appears fully-featured enough at this point.

Any insight appreciated! Thanks.

**Comment by ronag** [comment]
@petermelias It's in the backlog. We don't use `http2` -> `http2` at work.

**Comment by soumyakantiroychowdhury** [comment]
Any plan to support http1.1 -> http2 or http2 -> http2 proxying soon? Thanks.

**Comment by masx200** [comment]
> 有什么计划很快支持http1.1-> http2或http2-> http2代理？谢谢。


https://github.com/nxtedition/node-http2-proxy/issues/40

**Comment by ronag** [comment]
fixed in https://github.com/nxtedition/node-http2-proxy/commit/e0b93240b40bb4720c9dc903e6d6736df74d3fdb
